### ISSUE TITLE
Unknown block size code '0'

### ISSUE THREAD

**Issue by AdrianoSorgente** [teverett/paradoxReader#64]
I can't understand why this error is happening to me now:

`com.khubla.pdxreader.api.PDXReaderException: Exception in read
	at com.khubla.pdxreader.db.DBTableFile.read(DBTableFile.java:87)
	at com.khubla.pdxreader.MinAna.testRead(MinAna.java:22)
	at com.khubla.pdxreader.MinAna.main(MinAna.java:13)
Caused by: com.khubla.pdxreader.api.PDXReaderException: Exception in readHeaders
	at com.khubla.pdxreader.db.DBTableFile.readHeaders(DBTableFile.java:173)
	at com.khubla.pdxreader.db.DBTableFile.read(DBTableFile.java:68)
	... 2 more
Caused by: java.lang.Exception: Exception in read
	at com.khubla.pdxreader.db.DBTableHeader.read(DBTableHeader.java:534)
	at com.khubla.pdxreader.db.DBTableFile.readHeaders(DBTableFile.java:171)
	... 3 more
Caused by: java.lang.Exception: Unknown block size code '0'
	at com.khubla.pdxreader.db.DBTableHeader.read(DBTableHeader.java:410)
	... 4 more`

**Comment by AdrianoSorgente** [comment]
Hi Tom, I sent you an email (tom@khubla.com) with two file one works the other doesn't. thanks in advance for your help
